# Generated by Django 2.2.12 on 2020-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200612_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='type_name',
            field=models.CharField(max_length=64, verbose_name='资产类型'),
        ),
    ]
