# Generated by Django 2.2.12 on 2020-06-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200615_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': '业务系统信息', 'verbose_name_plural': '业务系统信息'},
        ),
        migrations.RemoveField(
            model_name='software',
            name='license_num',
        ),
        migrations.RemoveField(
            model_name='software',
            name='version',
        ),
        migrations.AddField(
            model_name='software',
            name='account_info',
            field=models.TextField(blank=True, null=True, verbose_name='账号信息'),
        ),
        migrations.AddField(
            model_name='software',
            name='all_url',
            field=models.TextField(blank=True, null=True, verbose_name='各节点访问地址'),
        ),
        migrations.AddField(
            model_name='software',
            name='assets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset', verbose_name='所属资产'),
        ),
        migrations.AddField(
            model_name='software',
            name='balanc_url',
            field=models.TextField(blank=True, null=True, verbose_name='访问地址'),
        ),
        migrations.AddField(
            model_name='software',
            name='domain_path',
            field=models.TextField(blank=True, null=True, verbose_name='域路径'),
        ),
        migrations.AddField(
            model_name='software',
            name='program_path',
            field=models.TextField(blank=True, null=True, verbose_name='程序路径'),
        ),
        migrations.AddField(
            model_name='software',
            name='soft_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='系统名称'),
        ),
        migrations.AddField(
            model_name='software',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.SubordinateUnits', verbose_name='所属单位'),
        ),
        migrations.AlterField(
            model_name='software',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
    ]
