# Generated by Django 2.2.12 on 2020-06-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20200616_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.SubordinateUnits', verbose_name='所属单位'),
        ),
    ]
