# Generated by Django 2.2.12 on 2020-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ip',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='IP'),
            preserve_default=False,
        ),
    ]
