# Generated by Django 2.2.12 on 2020-06-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=64, verbose_name='状态名称')),
            ],
            options={
                'verbose_name': '状态表',
                'verbose_name_plural': '状态表',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetStatus', verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, '其它'), (1, '硬件变更'), (2, '新增配件'), (3, '设备下线'), (4, '设备上线'), (5, '定期维护'), (6, '业务上线\\更新\\变更'), (7, '待审批资产变更'), (8, '业务系统变更'), (9, '资产类型变更'), (10, '软件类型变更'), (11, '系统设置变更')], default=4, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='software',
            name='assets',
            field=models.ManyToManyField(blank=True, to='assets.Asset', verbose_name='部署服务器'),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.SoftwareType', verbose_name='部署方式'),
        ),
    ]
