# Generated by Django 2.2.12 on 2020-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, '其他'), (1, '登陆'), (2, '退出'), (3, '登陆错误'), (4, '修改密码失败'), (5, '修改密码成功'), (6, '注册成功'), (7, '审批成功')], default=1, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '启用'), (1, '禁用'), (2, '审核')], default=0, verbose_name='账号状态'),
        ),
    ]
